[tools]
chezmoi = "latest"
delta = "latest"
gh = "latest"
go = "latest"
node = "lts"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:pnpm" = "latest"
pnpm = "latest"
starship = "latest"
uv = "latest"

